/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package searchroom;

import javax.swing.JOptionPane;
import static searchroom.home.Username;

/**
 *
 * @author medet
 */
public class ContactUs extends javax.swing.JFrame {

    /**
     * Creates new form ContactUs
     */
    static String Username;
    
    public ContactUs(String name) {
        Username = name;
        initComponents();
        this.setSize(1920,1080);
        this.setResizable(false);          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AboutUsP = new javax.swing.JPanel();
        MoreP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FNameTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FeedbackTf = new javax.swing.JTextArea();
        SendFeedbackB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RatingT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ContactUsCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        HomeM = new javax.swing.JMenu();
        SearchM = new javax.swing.JMenu();
        MyProfileM = new javax.swing.JMenu();
        AboutUsM = new javax.swing.JMenu();
        ContactUsM = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AboutUsP.setPreferredSize(new java.awt.Dimension(1920, 1080));
        AboutUsP.setLayout(null);

        MoreP.setBackground(new java.awt.Color(102, 255, 51));
        MoreP.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contact Us");
        MoreP.add(jLabel1);
        jLabel1.setBounds(0, 0, 1450, 100);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Name :");
        MoreP.add(jLabel3);
        jLabel3.setBounds(130, 100, 260, 70);

        FNameTf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MoreP.add(FNameTf);
        FNameTf.setBounds(650, 100, 330, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Your Feedback :");
        MoreP.add(jLabel5);
        jLabel5.setBounds(140, 460, 420, 80);

        FeedbackTf.setColumns(20);
        FeedbackTf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FeedbackTf.setRows(5);
        jScrollPane1.setViewportView(FeedbackTf);

        MoreP.add(jScrollPane1);
        jScrollPane1.setBounds(650, 420, 450, 270);

        SendFeedbackB.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SendFeedbackB.setText("Send Feedback");
        SendFeedbackB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendFeedbackBMouseClicked(evt);
            }
        });
        SendFeedbackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendFeedbackBActionPerformed(evt);
            }
        });
        MoreP.add(SendFeedbackB);
        SendFeedbackB.setBounds(390, 710, 490, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Rating :");
        MoreP.add(jLabel2);
        jLabel2.setBounds(130, 310, 230, 70);

        RatingT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RatingTKeyTyped(evt);
            }
        });
        MoreP.add(RatingT);
        RatingT.setBounds(650, 310, 330, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Hotel :");
        MoreP.add(jLabel4);
        jLabel4.setBounds(130, 190, 250, 70);

        ContactUsCB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ContactUsCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clairon Hotel", "The Mount Regency", "Liberty Park", "MGM Beach Resorts", "Delhi Empire Dx", "Radisson Hotel", "Grand Heritage Resort", "Sri Sri Residency", "The LaLit", "Mango Hotel", "Indana Palace", "Souvenir Prime", "The Ambassador", "Parle International", "The Oriental Residency", "Golden Chariot", "Noor-Us-Subah Palace", "Jehanuma Palace", "Shalimar Deluxe", "Golden Lakes Hotel" }));
        MoreP.add(ContactUsCB);
        ContactUsCB.setBounds(650, 200, 330, 60);

        AboutUsP.add(MoreP);
        MoreP.setBounds(310, 70, 1450, 800);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchroom/bckg5.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        AboutUsP.add(jLabel9);
        jLabel9.setBounds(0, 0, 1920, 970);

        getContentPane().add(AboutUsP);
        AboutUsP.setBounds(0, 0, 1920, 1080);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(1920, 126));

        HomeM.setText("HOME");
        HomeM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        HomeM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HomeM.setPreferredSize(new java.awt.Dimension(384, 24));
        HomeM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMMouseClicked(evt);
            }
        });
        jMenuBar1.add(HomeM);

        SearchM.setText("SEARCH");
        SearchM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SearchM.setPreferredSize(new java.awt.Dimension(384, 24));
        SearchM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMMouseClicked(evt);
            }
        });
        jMenuBar1.add(SearchM);

        MyProfileM.setText("MY PROFILE");
        MyProfileM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        MyProfileM.setPreferredSize(new java.awt.Dimension(384, 24));
        MyProfileM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyProfileMMouseClicked(evt);
            }
        });
        jMenuBar1.add(MyProfileM);

        AboutUsM.setText("ABOUT US");
        AboutUsM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        AboutUsM.setPreferredSize(new java.awt.Dimension(384, 24));
        AboutUsM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsMMouseClicked(evt);
            }
        });
        jMenuBar1.add(AboutUsM);

        ContactUsM.setText("CONTACT US");
        ContactUsM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ContactUsM.setPreferredSize(new java.awt.Dimension(384, 24));
        ContactUsM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactUsMMouseClicked(evt);
            }
        });
        jMenuBar1.add(ContactUsM);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendFeedbackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendFeedbackBActionPerformed
        
    }//GEN-LAST:event_SendFeedbackBActionPerformed

    private void HomeMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMMouseClicked
     
        this.dispose();
        new home(Username).setVisible(true);
    }//GEN-LAST:event_HomeMMouseClicked

    private void SearchMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMMouseClicked
        
        this.dispose();
        new SearchRoomUI(Username).setVisible(true);

    }//GEN-LAST:event_SearchMMouseClicked

    private void MyProfileMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileMMouseClicked
        
        this.dispose();
        new withback(Username).setVisible(true);

    }//GEN-LAST:event_MyProfileMMouseClicked

    private void AboutUsMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsMMouseClicked
        
        this.dispose();
        new AboutUs(Username).setVisible(true);
    }//GEN-LAST:event_AboutUsMMouseClicked

    private void ContactUsMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactUsMMouseClicked
        
        this.dispose();
        new ContactUs(Username).setVisible(true);
    }//GEN-LAST:event_ContactUsMMouseClicked

    private void RatingTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RatingTKeyTyped
                
                
                    
       
    }//GEN-LAST:event_RatingTKeyTyped

    private void SendFeedbackBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendFeedbackBMouseClicked
        Cursor c = new Cursor();
        c.insertinfo(FNameTf.getText(), FeedbackTf.getText());
        System.out.println(ContactUsCB.getSelectedItem().toString());
        c.Rating_Update(RatingT.getText(),ContactUsCB.getSelectedItem().toString());
         JOptionPane.showMessageDialog(null, "Thank you for your feedback");
    }//GEN-LAST:event_SendFeedbackBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactUs(Username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AboutUsM;
    private javax.swing.JPanel AboutUsP;
    private javax.swing.JComboBox<String> ContactUsCB;
    private javax.swing.JMenu ContactUsM;
    private javax.swing.JTextField FNameTf;
    private javax.swing.JTextArea FeedbackTf;
    private javax.swing.JMenu HomeM;
    private javax.swing.JPanel MoreP;
    private javax.swing.JMenu MyProfileM;
    private javax.swing.JTextField RatingT;
    private javax.swing.JMenu SearchM;
    private javax.swing.JButton SendFeedbackB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
