package searchroom;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static searchroom.home.Username;
import static searchroom.SearchResultsUI.Username;
import java.sql.*;
import javax.swing.*;
import static searchroom.AboutUs.Username;
import java.util.concurrent.ThreadLocalRandom;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author medet
 */
public class ModeOfPayment extends javax.swing.JFrame {

    /**
     * Creates new form ModeOfPayment
     */
    static String Username;
    int amount;
    String [] insert_array;
    String loc;
    
    
    public ModeOfPayment(String name) {
        Username = name;
        initComponents();
        //amount = (Integer.parseInt(insert_array[8])) * (Integer.parseInt(insert_array[2]));
        this.setSize(1920,1080);
        this.setResizable(false);
        //this.getAmount();
    }
    
   // amount = (Integer.parseInt(insert_array[8])) * (Integer.parseInt(insert_array[2]));
    
    
    public ModeOfPayment(String name,String [] insert_array) {
        
        Username = name;
        initComponents();
        this.setSize(1920,1080);
        this.setResizable(false);
        //this.getAmount();
        this.insert_array = insert_array;
        amount = ((Integer.parseInt(insert_array[8]))) * ((Integer.parseInt(insert_array[5])));
        loc=insert_array[0];
        amountLabel.setText(("Rs " + String.valueOf(amount)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGroungPanel = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JPanel();
        MakePaymentTitleL = new javax.swing.JLabel();
        CvvnumL = new javax.swing.JLabel();
        CreditCardNumL = new javax.swing.JLabel();
        CreditCardNumTf = new javax.swing.JTextField();
        TotalAmountL = new javax.swing.JLabel();
        MakePaymentB = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AadharCardTf = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        BackImageL = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        HomeM = new javax.swing.JMenu();
        SearchM = new javax.swing.JMenu();
        MyProfileM = new javax.swing.JMenu();
        AboutUsM = new javax.swing.JMenu();
        ContactUsM = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        BackGroungPanel.setLayout(null);

        ContentPanel.setBackground(new java.awt.Color(153, 255, 0));

        MakePaymentTitleL.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        MakePaymentTitleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MakePaymentTitleL.setText("MAKE PAYMENT");
        MakePaymentTitleL.setAlignmentX(0.5F);

        CvvnumL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CvvnumL.setText("CVV NUMBER :");

        CreditCardNumL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CreditCardNumL.setText("CREDIT CARD NUMBER :");

        CreditCardNumTf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        TotalAmountL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TotalAmountL.setText("TOTAL AMOUNT :");

        MakePaymentB.setBackground(new java.awt.Color(51, 51, 255));
        MakePaymentB.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        MakePaymentB.setText("Confirm Booking");
        MakePaymentB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MakePaymentBMouseClicked(evt);
            }
        });
        MakePaymentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakePaymentBActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 51, 51));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        amountLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        amountLabel.setText("The amount will be displayed here");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchroom/bckg7.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("AADHAR CARD NUMBER");

        AadharCardTf.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        PasswordField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(MakePaymentTitleL, javax.swing.GroupLayout.PREFERRED_SIZE, 1293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(286, 286, 286)
                                .addComponent(MakePaymentB)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ContentPanelLayout.createSequentialGroup()
                                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CvvnumL, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(28, 28, 28)
                                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AadharCardTf, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(ContentPanelLayout.createSequentialGroup()
                                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CreditCardNumL, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TotalAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CreditCardNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                                .addComponent(jLabel8)))))
                .addGap(121, 121, 121))
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(MakePaymentTitleL, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreditCardNumL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreditCardNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CvvnumL, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AadharCardTf, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(TotalAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(44, 44, 44))
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MakePaymentB)
                    .addComponent(backButton))
                .addGap(71, 71, 71))
        );

        BackGroungPanel.add(ContentPanel);
        ContentPanel.setBounds(190, 130, 1550, 790);

        BackImageL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchroom/bckg4.jpg"))); // NOI18N
        BackGroungPanel.add(BackImageL);
        BackImageL.setBounds(0, 0, 1920, 950);

        getContentPane().add(BackGroungPanel);
        BackGroungPanel.setBounds(0, 0, 1920, 1080);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(1920, 126));

        HomeM.setText("HOME");
        HomeM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        HomeM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HomeM.setPreferredSize(new java.awt.Dimension(384, 24));
        HomeM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMMouseClicked(evt);
            }
        });
        jMenuBar1.add(HomeM);

        SearchM.setText("SEARCH");
        SearchM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        SearchM.setPreferredSize(new java.awt.Dimension(384, 24));
        SearchM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMMouseClicked(evt);
            }
        });
        jMenuBar1.add(SearchM);

        MyProfileM.setText("MY PROFILE");
        MyProfileM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        MyProfileM.setPreferredSize(new java.awt.Dimension(384, 24));
        MyProfileM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyProfileMMouseClicked(evt);
            }
        });
        jMenuBar1.add(MyProfileM);

        AboutUsM.setText("ABOUT US");
        AboutUsM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        AboutUsM.setPreferredSize(new java.awt.Dimension(384, 24));
        AboutUsM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsMMouseClicked(evt);
            }
        });
        jMenuBar1.add(AboutUsM);

        ContactUsM.setText("CONTACT US");
        ContactUsM.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ContactUsM.setPreferredSize(new java.awt.Dimension(384, 24));
        ContactUsM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactUsMMouseClicked(evt);
            }
        });
        jMenuBar1.add(ContactUsM);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed
    
    /*private void getAmount(){
     SearchResultsUI1 s1 = new SearchResultsUI1();   
     amount =    s1.findCost();
     amountLabel.setText("'"+amount+"'");
    }*/
    
    
    private void MakePaymentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakePaymentBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MakePaymentBActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new SearchRoomUI(Username).setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void MakePaymentBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MakePaymentBMouseClicked
            // TODO add your handling code here:
            Cursor c = new Cursor();
            if(AadharCardTf.getText().isEmpty()||CreditCardNumTf.getText().isEmpty()||PasswordField.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "All of the entries are not filled");
            }            
            
            else{
                if(PasswordField.getText().length()!=3 ){
                    JOptionPane.showMessageDialog(null, "CVV Number is incorrect");
                }
                else if(c.validateVerhoeff(AadharCardTf.getText())==false){
                    JOptionPane.showMessageDialog(null, "Invalid Aadhar Card Number");
                }
                else if(CreditCardNumTf.getText().length()!=16){
                    JOptionPane.showMessageDialog(null, "Invalid Credit Card Number");
                }
                else{
                    
                    Cursor conn = new Cursor();
                    
                    //SearchResultsUI1 makepayment = new SearchResultsUI1 ();
                    //int randomNum = makepayment.addToDB();
                    
                    String query = "Insert into 'GuestData' Values('"+insert_array[0]+"','"+insert_array[1]+"','"+insert_array[2]+"','"+insert_array[3]+"','"+insert_array[4]+"','"+insert_array[5]+"','"+insert_array[6]+"','"+insert_array[7]+"','"+insert_array[8]+"')";
                    conn.insert(query);
                    
                    this.setVisible(false);
                    this.dispose();
                    new home(Username).setVisible(true);
                    JOptionPane.showMessageDialog(null, "Your transaction has been successfully completed and reference no is '"+insert_array[7]+"'");
                    
                }
            }
    }//GEN-LAST:event_MakePaymentBMouseClicked

    private void HomeMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Changing pages at payment gateway is not allowed");
    }//GEN-LAST:event_HomeMMouseClicked

    private void SearchMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Changing pages at payment gateway is not allowed");
    }//GEN-LAST:event_SearchMMouseClicked

    private void MyProfileMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyProfileMMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Changing pages at payment gateway is not allowed");
    }//GEN-LAST:event_MyProfileMMouseClicked

    private void AboutUsMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsMMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Changing pages at payment gateway is not allowed");
    }//GEN-LAST:event_AboutUsMMouseClicked

    private void ContactUsMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactUsMMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Changing pages at payment gateway is not allowed");
    }//GEN-LAST:event_ContactUsMMouseClicked

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldKeyPressed

    private void PasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
            || (vchar == KeyEvent.VK_BACK_SPACE)
            || (vchar == KeyEvent.VK_DELETE)){            
            evt.consume();
        }
    }//GEN-LAST:event_PasswordFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeOfPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeOfPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeOfPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeOfPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeOfPayment(Username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AadharCardTf;
    private javax.swing.JMenu AboutUsM;
    private javax.swing.JPanel BackGroungPanel;
    private javax.swing.JLabel BackImageL;
    private javax.swing.JMenu ContactUsM;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JLabel CreditCardNumL;
    private javax.swing.JTextField CreditCardNumTf;
    private javax.swing.JLabel CvvnumL;
    private javax.swing.JMenu HomeM;
    private javax.swing.JButton MakePaymentB;
    private javax.swing.JLabel MakePaymentTitleL;
    private javax.swing.JMenu MyProfileM;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JMenu SearchM;
    private javax.swing.JLabel TotalAmountL;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
