/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package searchroom;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import static searchroom.home.Username;
/**
 *
 * @author PRANJAL
 */
public class SearchRoomUI extends javax.swing.JFrame {

    /**
     * Creates new form SearchRoomUI
     */
    static String Username;
    
    public SearchRoomUI(String name) {
        Username = name;
        initComponents();
        this.setSize(1920,1080);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        searchPanel = new javax.swing.JPanel();
        entryPanel = new javax.swing.JPanel();
        locationLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        guestText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        fromDate = new datechooser.beans.DateChooserCombo();
        toDate = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        locationComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        noofroomText = new javax.swing.JTextField();
        bckgLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        searchMenu = new javax.swing.JMenu();
        profileMenu = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenu();
        contactMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        searchPanel.setLayout(null);

        entryPanel.setBackground(new java.awt.Color(60, 175, 247));
        entryPanel.setLayout(null);

        locationLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        locationLabel.setText("LOCATION :");
        entryPanel.add(locationLabel);
        locationLabel.setBounds(90, 30, 207, 77);

        fromLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fromLabel.setText("NUMBER OF ROOMS : ");
        entryPanel.add(fromLabel);
        fromLabel.setBounds(90, 320, 264, 77);

        toLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        toLabel.setText("FROM DATE :");
        entryPanel.add(toLabel);
        toLabel.setBounds(90, 140, 207, 77);

        roomLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        roomLabel.setText("TO DATE :");
        entryPanel.add(roomLabel);
        roomLabel.setBounds(90, 220, 207, 77);

        guestText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guestText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                guestTextKeyTyped(evt);
            }
        });
        entryPanel.add(guestText);
        guestText.setBounds(480, 420, 341, 77);

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayResults(evt);
            }
        });
        entryPanel.add(searchButton);
        searchButton.setBounds(253, 537, 395, 96);

        Dimension size = fromDate.getCalendarPreferredSize();
        size.width += 90;
        fromDate.setCalendarPreferredSize(size);
        fromDate.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 18));
        entryPanel.add(fromDate);
        fromDate.setBounds(480, 150, 341, 67);

        Dimension size1 = toDate.getCalendarPreferredSize();
        size1.width += 90;
        toDate.setCalendarPreferredSize(size1);
        toDate.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 18));
        entryPanel.add(toDate);
        toDate.setBounds(480, 250, 341, 57);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Note : Max 3 people in a room");
        entryPanel.add(jLabel1);
        jLabel1.setBounds(110, 380, 220, 40);

        locationComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Delhi", "Jaipur", "Chennai", "Bhopal", "Kolkata" }));
        locationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboBoxActionPerformed(evt);
            }
        });
        entryPanel.add(locationComboBox);
        locationComboBox.setBounds(480, 60, 340, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("TOTAL GUESTS :");
        entryPanel.add(jLabel2);
        jLabel2.setBounds(90, 430, 240, 60);

        noofroomText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noofroomText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noofroomTextKeyTyped(evt);
            }
        });
        entryPanel.add(noofroomText);
        noofroomText.setBounds(480, 330, 341, 77);

        searchPanel.add(entryPanel);
        entryPanel.setBounds(500, 90, 890, 700);

        bckgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchroom/bckg1.jpg"))); // NOI18N
        searchPanel.add(bckgLabel);
        bckgLabel.setBounds(0, 0, 1920, 950);

        menuBar.setPreferredSize(new java.awt.Dimension(1920, 126));

        homeMenu.setText("HOME");
        homeMenu.setToolTipText("Homepage");
        homeMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homeMenu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        homeMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        homeMenu.setPreferredSize(new java.awt.Dimension(384, 24));
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        menuBar.add(homeMenu);

        searchMenu.setText("SEARCH ");
        searchMenu.setToolTipText("Search for hotels");
        searchMenu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        searchMenu.setPreferredSize(new java.awt.Dimension(384, 24));
        searchMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMenuMouseClicked(evt);
            }
        });
        menuBar.add(searchMenu);

        profileMenu.setText("MY PROFILE");
        profileMenu.setToolTipText("View your account details");
        profileMenu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        profileMenu.setPreferredSize(new java.awt.Dimension(384, 24));
        profileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMenuMouseClicked(evt);
            }
        });
        menuBar.add(profileMenu);

        aboutMenu.setText("ABOUT US");
        aboutMenu.setToolTipText("Get to know more about our sites and other services");
        aboutMenu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        aboutMenu.setPreferredSize(new java.awt.Dimension(384, 24));
        aboutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMenuMouseClicked(evt);
            }
        });
        menuBar.add(aboutMenu);

        contactMenu.setText("CONTACT US");
        contactMenu.setToolTipText("Contact informtation");
        contactMenu.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        contactMenu.setPreferredSize(new java.awt.Dimension(384, 24));
        contactMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMenuMouseClicked(evt);
            }
        });
        menuBar.add(contactMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayResults(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayResults
        // TODO add your handling code here:
        Object l = locationComboBox.getSelectedItem();
        String Location = l.toString();
        
        int from_date = Integer.parseInt(fromDate.getText().split("/", 0)[0]);
        int from_month = Integer.parseInt(fromDate.getText().split("/", 0)[1]);
        int from_year = Integer.parseInt(fromDate.getText().split("/", 0)[2]);
        int to_date = Integer.parseInt(toDate.getText().split("/", 0)[0]);
        int to_month = Integer.parseInt(toDate.getText().split("/", 0)[1]);
        int to_year = Integer.parseInt(toDate.getText().split("/", 0)[2]);
        int tot_room;
        int tot_guest;
       
        
        int counter_date = 0;
        int counter_room = 0;
        try{
            if (from_year > to_year) throw new Exception();
            else if (from_month > to_month && from_year == to_year) throw new Exception();
            else if (from_date > to_date && from_month == to_month && from_year == to_year) throw new Exception();
            else counter_date ++;
        }    
       catch (Exception e){
            JOptionPane.showMessageDialog(null, "Please enter correct check-in and check-out dates");
       }
       
        try{
            tot_room = Integer.parseInt(noofroomText.getText());
            tot_guest = Integer.parseInt(guestText.getText());
           if ((tot_room*3 < tot_guest) || (tot_room >150)) throw new Exception();
           else counter_room ++;
       }
       catch (Exception e){
            JOptionPane.showMessageDialog(null, "Accomodation not possible.");          
       } 
       finally{
            if (counter_date == 1 && counter_room == 1){
                /*int[][] roomCount = new int[4][60];
                for(int i=0;i<4;i++){
                    for(int j=0;j<60;j++){
                        roomCount[i][j] = 150;
                    }
                }*/
                
                boolean isAvailable[];
                Cursor c1=new Cursor();
                isAvailable = c1.roomCount("SELECT * FROM 'GuestData' WHERE Location = '"+Location+"'",noofroomText.getText());
                
                this.setVisible(false);
                this.dispose();
                new SearchResultsUI(Username, isAvailable,Location).setVisible(true);
            }
       }
        
        
    }//GEN-LAST:event_displayResults

    private void locationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationComboBoxActionPerformed

    private void noofroomTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noofroomTextKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
            || (vchar == KeyEvent.VK_BACK_SPACE)
            || (vchar == KeyEvent.VK_DELETE)){
        evt.consume();   
    }
    }//GEN-LAST:event_noofroomTextKeyTyped

    private void guestTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guestTextKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
            || (vchar == KeyEvent.VK_BACK_SPACE)
            || (vchar == KeyEvent.VK_DELETE)){
        evt.consume();   
    }        
    }//GEN-LAST:event_guestTextKeyTyped

    private void searchMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMenuMouseClicked

    private void profileMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMenuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new withback(Username).setVisible(true);
    }//GEN-LAST:event_profileMenuMouseClicked

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new home(Username).setVisible(true);
    }//GEN-LAST:event_homeMenuMouseClicked

    private void aboutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMenuMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new AboutUs(Username).setVisible(true);
    }//GEN-LAST:event_aboutMenuMouseClicked

    private void contactMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMenuMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ContactUs(Username).setVisible(true);
    }//GEN-LAST:event_contactMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchRoomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchRoomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchRoomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchRoomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchRoomUI(Username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JLabel bckgLabel;
    private javax.swing.JMenu contactMenu;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JPanel entryPanel;
    private datechooser.beans.DateChooserCombo fromDate;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField guestText;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField noofroomText;
    private javax.swing.JMenu profileMenu;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JMenu searchMenu;
    private javax.swing.JPanel searchPanel;
    private datechooser.beans.DateChooserCombo toDate;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
