/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resultsUI;

/**
 *
 * @author PRANJAL
 */
public class resultsPanelUI extends javax.swing.JPanel {

    /**
     * Creates new form resultsPanelUI
     */
    public resultsPanelUI() {
        initComponents();
    }
    
    public javax.swing.JPanel getPanelRef(){
        return resultPanel;
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultPanel = new javax.swing.JPanel();
        displayPanel = new javax.swing.JPanel();
        displayLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        payementButton = new javax.swing.JButton();
        bckgLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1920, 954));

        resultPanel.setPreferredSize(new java.awt.Dimension(1920, 954));
        resultPanel.setLayout(null);

        displayPanel.setBackground(new java.awt.Color(204, 255, 0));

        displayLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        displayLabel.setText("THESE ARE THE AVAILABLE HOTELS : ");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                .addContainerGap())
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(715, Short.MAX_VALUE))
        );

        resultPanel.add(displayPanel);
        displayPanel.setBounds(410, 80, 1060, 770);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        resultPanel.add(backButton);
        backButton.setBounds(60, 750, 320, 100);

        payementButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        payementButton.setText("PROCEED TO PAYMENT");
        payementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payementButtonActionPerformed(evt);
            }
        });
        resultPanel.add(payementButton);
        payementButton.setBounds(1540, 740, 320, 100);

        bckgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchroom/bckg2.jpg"))); // NOI18N
        resultPanel.add(bckgLabel);
        bckgLabel.setBounds(0, 0, 1920, 950);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void payementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payementButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payementButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bckgLabel;
    private javax.swing.JLabel displayLabel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton payementButton;
    private javax.swing.JPanel resultPanel;
    // End of variables declaration//GEN-END:variables
}
