/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

/**
 *
 * @author Saarthak Jain
 */
public class login1 extends javax.swing.JFrame {

    /**
     * Creates new form login1
     */
    public login1() {
        initComponents();
        this.setSize(1000, 1000);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        re_password = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        contact = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saarthak Jain\\Desktop\\Welcome-flat.fw_-300x208.png")); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jTextField1.setToolTipText("Username must be unique");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(510, 190, 330, 43);

        username.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("USERNAME :");
        getContentPane().add(username);
        username.setBounds(160, 190, 171, 43);

        password.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("PASSWORD :");
        getContentPane().add(password);
        password.setBounds(160, 260, 171, 40);

        jPasswordField1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jPasswordField1.setToolTipText("Password should be at least 6 characters long.");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(510, 260, 330, 40);

        jPasswordField2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jPasswordField2.setToolTipText("The password must match ");
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(510, 330, 330, 41);

        re_password.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        re_password.setForeground(new java.awt.Color(255, 255, 255));
        re_password.setText("CONFIRM PASSWORD : ");
        getContentPane().add(re_password);
        re_password.setBounds(160, 330, 340, 41);

        jTextField2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jTextField2.setToolTipText("Please enter valid phone number");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(510, 400, 330, 41);

        contact.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setText("CONTACT :");
        getContentPane().add(contact);
        contact.setBounds(160, 400, 171, 41);

        dob.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        dob.setText("DATE OF BIRTH :");
        getContentPane().add(dob);
        dob.setBounds(160, 470, 310, 41);

        jTextField3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jTextField3.setToolTipText("Format : DD-MM-YYYY");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(510, 470, 330, 41);

        email.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("EMAIL ID :");
        getContentPane().add(email);
        email.setBounds(160, 540, 171, 41);

        jTextField4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jTextField4.setToolTipText("Enter correct email id");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(510, 540, 330, 41);

        address.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("ADDRESS :");
        getContentPane().add(address);
        address.setBounds(160, 620, 177, 41);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jButton1.setText("RESET");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 830, 200, 60);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 620, 330, 123);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(570, 830, 200, 60);
        jButton2.getAccessibleContext().setAccessibleName("SIGN UP ");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saarthak Jain\\Desktop\\welcome-transparent-png-1.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 10, 530, 160);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Saarthak Jain\\Desktop\\gradient-background-26046-26731-hd-wallpapers.jpg.png")); // NOI18N
        jLabel2.setLabelFor(address);
        jLabel2.setText("ddsdsdsdsdsdsddd");
        jLabel2.setPreferredSize(new java.awt.Dimension(1000, 1000));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 1000, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel password;
    private javax.swing.JLabel re_password;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
